### ISSUE TITLE
VueSound not found

### ISSUE THREAD

**Issue by MuhammadWaseem0006** [kimlarocca/vue-sound#3]
In Vue 2 app, when I import VueSound from node_modules like
import VueSound from 'vue-sound';
then console returns the following error;
vue-sound not  @found;
please help me.

**Comment by emmachuche** [comment]
same. problem

**Comment by kimlarocca** [comment]
Hi! I've upgraded this to Vue 3 and fixed this issue, and the readme has been updated. Sorry for the late reply!
